apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compass-demo-repo-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/cze-dk/crossplane-github
    targetRevision: HEAD
    path: chart
    helm:
      releaseName: compass-demo-repo-backend
      parameters:
        - name: github.repository
          value: compass-demo-repo-backend
        - name: application.name
          value: compass-demo-repo-backend
        - name: application.host
          value: compass-demo-repo-backend.acme.com
        - name: application.project
          value: myproject
        - name: application.ownerId
          value: ari:cloud:identity::team/0b56fdaa-37e2-487e-b770-b271bb4e76a2
        - name: hyperscaler
          value: google
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
