configs:
  secret:
    argocdServerAdminPassword: "$2y$10$XhmBtqrHeXDUkIaNbIZvrOVkhUtwipbrIX9CVJhDOTToGZgrOGsf"
    argocdServerAdminPasswordMtime: "2021-11-08T15:04:05Z"
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 30s
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.rancher.localhost
